// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RescueSphere.Api.Data;

#nullable disable

namespace Rescue_Sphere.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.HelpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SupportCategoryId");

                    b.ToTable("HelpRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(9022),
                            Description = "Ailemiz için yardım talep ediyoruz, 3 kişilik aile",
                            IsDeleted = false,
                            Location = "İstanbul, Sultangazi",
                            Priority = 2,
                            RequestedByUserId = 4,
                            Status = 0,
                            SupportCategoryId = 1,
                            Title = "Acil Gıda Yardımı"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(9026),
                            Description = "Deprem nedeniyle evim hasar gördü, geçici barınma yardımı istiyorum",
                            IsDeleted = false,
                            Location = "İzmir, Konak",
                            Priority = 3,
                            RequestedByUserId = 5,
                            Status = 1,
                            SupportCategoryId = 2,
                            Title = "Geçici Barınma İhtiyacı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(9030),
                            Description = "Yaşlı anne için ilaç ve tıbbi malzeme gerekli",
                            IsDeleted = false,
                            Location = "Ankara, Çankaya",
                            Priority = 1,
                            RequestedByUserId = 4,
                            Status = 0,
                            SupportCategoryId = 3,
                            Title = "Sağlık Desteği"
                        });
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.SupportCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupportCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(7074),
                            Description = "Yiyecek ve içecek yardımı",
                            IsDeleted = false,
                            Name = "Gıda"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(7078),
                            Description = "Acil barınma ve konaklama yardımı",
                            IsDeleted = false,
                            Name = "Barınma"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(7081),
                            Description = "Tıbbi yardım ve sağlık hizmetleri",
                            IsDeleted = false,
                            Name = "Sağlık"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 572, DateTimeKind.Utc).AddTicks(7083),
                            Description = "Taşınma ve ulaştırma yardımı",
                            IsDeleted = false,
                            Name = "Nakliye"
                        });
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 15, 712, DateTimeKind.Utc).AddTicks(9213),
                            Email = "admin@rescuesphere.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$38ma4bszbKYX97g.CbBP0ONn5dugAG4YUMqrrva33fVBhop/dBnYW",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 15, 928, DateTimeKind.Utc).AddTicks(7349),
                            Email = "ali@rescuesphere.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$XfIi/VEL6MvWvOlBg5zrR.qu36QEdMzMtI3q4wX0xzaVPimKcRnbu",
                            Role = 1,
                            Username = "volunteer_ali"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 139, DateTimeKind.Utc).AddTicks(9362),
                            Email = "fatma@rescuesphere.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$LmH/GbvWxgILA8MKZr6L1eQZMQrdMNGrgLbn9ucMV1ZpuHt6VYnl.",
                            Role = 1,
                            Username = "volunteer_fatma"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 351, DateTimeKind.Utc).AddTicks(5748),
                            Email = "mehmet@rescuesphere.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$UnT3YNjyyl678vpGCfTDPu28Ltz.aRiZ.dRqiTxwAu04uwt0a.LLG",
                            Role = 0,
                            Username = "citizen_mehmet"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 571, DateTimeKind.Utc).AddTicks(661),
                            Email = "zeynep@rescuesphere.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$ECalResVtVoGBMQdT9LNKufdqMbaBOO.6DLcCq1CLUA68AkFVvXgm",
                            Role = 0,
                            Username = "citizen_zeynep"
                        });
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.VolunteerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HelpRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HelpRequestId");

                    b.HasIndex("VolunteerUserId");

                    b.ToTable("VolunteerAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2026, 1, 10, 18, 16, 16, 573, DateTimeKind.Utc).AddTicks(17),
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 573, DateTimeKind.Utc).AddTicks(166),
                            HelpRequestId = 1,
                            IsDeleted = false,
                            Status = 0,
                            VolunteerUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2026, 1, 10, 18, 16, 16, 573, DateTimeKind.Utc).AddTicks(169),
                            CreatedAt = new DateTime(2026, 1, 10, 18, 16, 16, 573, DateTimeKind.Utc).AddTicks(170),
                            HelpRequestId = 2,
                            IsDeleted = false,
                            Status = 1,
                            VolunteerUserId = 3
                        });
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.HelpRequest", b =>
                {
                    b.HasOne("RescueSphere.Api.Domain.Entities.User", "RequestedByUser")
                        .WithMany("HelpRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RescueSphere.Api.Domain.Entities.SupportCategory", "SupportCategory")
                        .WithMany("HelpRequests")
                        .HasForeignKey("SupportCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByUser");

                    b.Navigation("SupportCategory");
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.VolunteerAssignment", b =>
                {
                    b.HasOne("RescueSphere.Api.Domain.Entities.HelpRequest", "HelpRequest")
                        .WithMany("VolunteerAssignments")
                        .HasForeignKey("HelpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RescueSphere.Api.Domain.Entities.User", "VolunteerUser")
                        .WithMany("VolunteerAssignments")
                        .HasForeignKey("VolunteerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelpRequest");

                    b.Navigation("VolunteerUser");
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.HelpRequest", b =>
                {
                    b.Navigation("VolunteerAssignments");
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.SupportCategory", b =>
                {
                    b.Navigation("HelpRequests");
                });

            modelBuilder.Entity("RescueSphere.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("HelpRequests");

                    b.Navigation("VolunteerAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
